@Author: Ritika Patidar
 @Date  : 2021-03-04 01:42:38
 @Last Modified by  : Ritika Patidar
 @Last Modified time : 2021-03-04 01:42:38
 @Title : add an extra column to an numpy array

In [15]:
import numpy as np 
import sys
import os
sys.path.insert(0,os.path.abspath("LogFile"))
import loggerfile

In [16]:
def add_extra_column(first_row_column,second_row_column):
    """
    Description:
        this function define for add extra column on existing nd array
    Parameter:
        first_row_column (int) : given by user for add column in first row
        second_row_column (int) : given by user for add column in second row
    Return:
        if extra added to existing nd array then it returns successfully add extra column
    """
    try:
        original_array=np.array([[10,20,30], [40,50,60]])
        added_columns=np.array([[first_row_column],[second_row_column]])
        append_ndarray=np.append(original_array,added_columns,axis=1)
        loggerfile.Logger("info","extra column added")
        print("======================= original array ========================\n{0}".format(original_array))
        print("======================== after adding extra coulumn\n {0}\n {1}".format(added_columns,append_ndarray))
        return "successfully add extra column"
    except Exception as error:
        loggerfile.Logger("error","{0} error occure".format(error))


In [17]:
def main():
    """
    Description:
        this function define for take input from the user and call add_extra_column
    Parameter:
        None
    Return:
        None
    """
    try:
        first_row_column=int(input("enter first row column interger only: "))
        second_row_column=int(input("enter second row column interger only: "))
        add_extra_column(first_row_column,second_row_column)
        loggerfile.Logger("info","successfull take input from user and call add_extra_column function")
    except ValueError as error:
        loggerfile.Logger("error","{0} error occure".format(error))
    except Exception as error:
        loggerfile.Logger("error","{0} error occure".format(error))
main()

======================= original array ========================
[[10 20 30]
 [40 50 60]]
======================== after adding extra coulumn
 [[10]
 [11]]
 [[10 20 30 10]
 [40 50 60 11]]
