
 @Author: Ritika Patidar
 @Date  : 2021-03-03 10:17:38
 @Last Modified by  : Ritika Patidar
 @Last Modified time : 2021-03-03 10:17:38
 @Title :add a border (filled with 0's) around an existing array



In [1]:
import numpy as np 
created_array=np.ones((3,3))
print("====================== Original array =======================\n{0}".format(created_array))
created_array = np.pad(created_array, pad_width=1, mode='constant', constant_values=0)
print("====================== add boarder wth filled zeros =======================\n{0}".format(created_array))

====================== Original array =======================
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
====================== add boarder wth filled zeros =======================
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
