
 @Author: Ritika Patidar
 @Date  : 2021-03-03 10:29:38
 @Last Modified by  : Ritika Patidar
 @Last Modified time : 2021-03-03 10:29:38
 @Title : create a 8x8 matrix and fill it with a checkerboard pattern


In [1]:
import numpy as np 
created_array=np.zeros((8,8))
print("====================== Original array =======================\n{0}".format(created_array))
created_array[1::2,::2]=1
created_array[::2,1::2]=1
print("====================== add boarder wth filled zeros =======================\n{0}".format(created_array))

====================== Original array =======================
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
====================== add boarder wth filled zeros =======================
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
