
 @Author: Ritika Patidar
 @Date: 2021-03-2 22:26
 @Last Modified by: Ritika Patidar
 @Last Modified time: 2021-03-2 22:26 
 @Title :  create 3x3 matrix value ranging from 2 to 11  



In [3]:
import numpy as np
matrix_3x3 =  np.arange(2, 11).reshape(3,3)
print(matrix_3x3)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
