
 @Author: Ritika Patidar
 @Date  : 2021-03-03 10:42:38
 @Last Modified by  : Ritika Patidar
 @Last Modified time : 2021-03-03 10:42:38
 @Title : convert a list and tuple into arrays



In [2]:
import numpy as np 
user_defined_list=[1, 2, 3, 4, 5, 6, 7, 8]
print("====================== Original List =======================\n{0}".format(user_defined_list))
converted_array=np.asarray(user_defined_list)
print("====================== List converted into nd arrays =======================\n{0}".format(converted_array))
user_defined_tuple=([8, 4, 6], [1, 2, 3])
print("====================== Original Tuple =======================\n{0}".format(user_defined_tuple))
converted_tuple=np.asarray(user_defined_tuple)
print("====================== Tuple converted into nd arrays =======================\n{0}".format(converted_tuple))

====================== Original List =======================
[1, 2, 3, 4, 5, 6, 7, 8]
====================== List converted into nd arrays =======================
[1 2 3 4 5 6 7 8]
====================== Original Tuple =======================
([8, 4, 6], [1, 2, 3])
====================== Tuple converted into nd arrays =======================
[[8 4 6]
 [1 2 3]]
