@Author: Ritika Patidar
 @Date  : 2021-03-04 : 01:42:38
 @Last Modified by  : Ritika Patidar
 @Last Modified time : 2021-03-04 01:42:38
 @Title : create an array of (3, 4) shape, multiply every element value by 3 and display the new array

In [8]:
import numpy as np 
user_defined_ndarray=np.arange(12).reshape(3,4)
clone_user_defined_ndarray=user_defined_ndarray.copy()
for element in np.nditer(user_defined_ndarray,op_flags=['readwrite']):
    element[...] = 3 * element
print("======================== Original ndrray =================================\n{0}".format(clone_user_defined_ndarray))
print("======================== after multiply by three ===================================\n{0}".format(user_defined_ndarray))

======================== Original ndrray =================================
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
======================== after multiply by three ===================================
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
