 @Author: Ritika Patidar
 @Date  : 2021-03-03 10:42:38
 @Last Modified by  : Ritika Patidar
 @Last Modified time : 2021-03-03 10:42:38
 @Title : concatenate two 2-dimensional arrays

In [26]:
import numpy as np 


In [27]:
user_defined_ndarray1=np.array([[0, 1, 3], [5, 7, 9]])
user_defined_ndarray2=np.array([[0, 2, 4], [6, 8, 10]])
concatenate_ndarray=np.concatenate((user_defined_ndarray1,user_defined_ndarray2),axis=1)
print("==============user_defined_ndarray1===========\n{0}\n================ user_defined_ndarray2==========\n{1}\n=====================concatenate array ======================\n{2}".format(user_defined_ndarray1,user_defined_ndarray2,concatenate_ndarray))

==============user_defined_ndarray1===========
[[0 1 3]
 [5 7 9]]
================ user_defined_ndarray2==========
[[ 0  2  4]
 [ 6  8 10]]
=====================concatenate array ======================
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
