 @Author: Ritika Patidar
 @Date  : 2021-03-04 00:52:38
 @Last Modified by  : Ritika Patidar
 @Last Modified time : 2021-03-04 00:52:38
 @Title : create a 3-D array with ones on a diagonal and zeros elsewhere

In [6]:
import numpy as np
import os
import sys
sys.path.insert(0,os.path.abspath("LogFile"))
import loggerfile

In [7]:
try:
    Dimension_array=int(input("enter dimension of array: "))
    created_array=np.eye(Dimension_array)
    print("=================================================\ncreate a 3-D array with ones on a diagonal and zeros elsewhere is\n {0}".format(created_array))
    loggerfile.Logger("info","successfully created 3-D array with ones on a diagonal and zeros elsewhere")
except ValueError as error:
    loggerfile.Logger("error","{0} error occured".format(error))
except Exception as error:
    loggerfile.Logger("error","{0} error occured".format(error))


create a 3-D array with ones on a diagonal and zeros elsewhere is
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
