'''
 @Author: Ritika Patidar
 @Date  : 2021-03-03 00:28:28
 @Last Modified by  : Ritika Patidar
 @Last Modified time : 2021-03-03 00:28:28
 @Title :To create a 2d array with 1 on the border and 0 inside
'''


In [1]:
import numpy as np 
created_array=np.ones((5,5))
print("====================== Original array =======================\n{0}".format(created_array))
created_array[1:-1,1:-1]=0
print("====================== 1 on the border and 0 inside in the array =======================\n{0}".format(created_array))

====================== Original array =======================
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
====================== 1 on the border and 0 inside in the array =======================
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
